# PROBLEM 2
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.
require 'pry'

a = [1,2]

loop do
  x = a.last + a[a.length-2] 
  if x < 4000000
    a.push x
  else
    break
  end
end

# puts a

b = []

a.each do |x|
  if x.even?
    b.push x
  end
end

# puts b

sum = b.reduce :+

puts sum
